services:
  mongodb:
    image: "mongo:latest"
    ports:
      - 27018:27017
    volumes:
      - mongodb_data:/data/db
  web:
    build: .
    command: ash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3001:3000"
    depends_on:
      - mongodb
    stdin_open: true
    tty: true
volumes:
  mongodb_data:
    driver: local