development:
  clients:
    default:
      database: myapp_development
      hosts:
        - 'mongodb:27017'
  options:
    raise_not_found_error: false

test:
  clients:
    default:
      database: myapp_test
      hosts:
        - 'mongodb:27017'
  options:
    raise_not_found_error: false